# Generated by Django 3.1.5 on 2021-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('filetype_id', models.CharField(max_length=50)),
                ('company_id', models.CharField(max_length=50)),
                ('file_creation_date', models.DateField(max_length=10)),
                ('file_creation_time', models.DateTimeField()),
                ('file_generation_no', models.CharField(max_length=50)),
            ],
        ),
    ]
